server:
  port: 8083

spring:
  datasource:
    url: '{cipher}AQByp2Uo33JT68+cTzNMJr2eAzHslkj9XTwEynWAX5dnIWAROH3J7zqOvF7adMilWfEoofW6GJhAka3yFk6/ePCmq0UrVR6JVQZ5afs1k9u0tuMdd4tLOvPPtIMWYl7LrjXCaeW+zFZGHb3c/CgVQ0YnJdfvjWSkzkKNbRHReMP66QZ1d507H47jmOEGaroUT70H7RugayGirv+fK3IyXZDKI1SNmZID1uH22+ga3VPMs1xnFxe+h3VMEbzHlGTrUzihO5CLroH16p/EFV0wC4bxPiZFIXp4uWJDI+/v2S7h1c1ZXvxe6BN8bluSTQ5W06ndZRvBr5rPakdlPHGIYfjbchZhUjdhBOp2NrzRUTon1baLFsvQwfUYO+3IAwCWXBRWMl8F2DzhjGfVkpXg6brUxw2Nf2LOG9sjx8uNYHd/ZfqM4P2YSCftHQ/X9Ym2WMM='

    #AQAoIsrbv7jxf03840aiof/PLovvsFWVgYQObCqziJ9kEpvb4XlLclTrFJf7sVPnbJFgHHneDK9K95cGromWgdQctqfIJP+8chn9CuCI4Kv9dqkOKbThiuWDCQHE0sHNrvI998FDgLlJ1xSbIoZxeyVhyoX5ctvMz2qEsQ2w9VAItsnfyTgFo4Hj1zojPWCNl07iwSjh25J+O/YzG5sqCv+nPhjr6NNDIT7CfHt526tSRPJBe5lAm/uewz7FvX3PabmZA8pyt/kFJJm2naguXCzJGWqcO8ysSqHn1dSHntr4htvoSQcb2bgHmv6a3FbQQYdWuM9xyuEiOyiJA0nW1DMGp7Recjoq7eP5OvOjOhbDYkvPQCAuEdf9D3wI5B7WptJEt1XFkkuTnjW1Rd7ks1lFnP6LocgfQhqw58XXLRLFgdazIaUn+doKvhQ8urbHf3k=
  jpa:
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: lucene/indexes
lucene:
  queryParser:
    leadingWildcard: true

notification:
  ribbon:
    listOfServers: http://localhost:8003