server:
  port: 8082

spring:
  datasource:
    url: '{cipher}AQAt/Pw182GHS83NQ0xcglTJwiEq1YI0wyvbJJdKQ7EgzS+7VFXDx/ZtivpvxAs7MhDJ/1S3XdbTwDpVKXMaAoWKxBssjkZr4YvIMkQYK2/FGlOOSVpuT8YqjSNg52kY0Hpq4q/VM1C0QDVa+TOgbJjjxpOHQp8dbWk8iQbIZr5JVESn+Gg3fKdwtDDSDbU9dVB3diOB0jbyBweS+tVO7P+ElzLpTJCMKwiCodQ/7DvUj24t4BfxzHhNHVw179+lZp1/Xnf2V2D65p3Ua8nVP/nj3UmcuvVsRFyR5Sihdl+eLkWOP/5GaMu/0P/QjyeTm2SdXIdsxrgEcLgGSkFWfBe7jFCip+EjdSO5dWZxawHciapv/5rT6imIUcgIYVTNV2M7z8QwYFFJ8uXqKVVjLoZjXaTWAjU/mKfm+QA06dFItb7xu4vTH02Zd4v+uugU0s8='

file:
  storage:
    enabled: true
    bucketName: '{cipher}AQCG8+0RR3/N9KZFBxwvLFWGJUbl3bTeEgRji5pD6agnhccV1Ur1d2DjrFfjuFRQowRLbfYrGtiTReJhH/cDFWQ9bdwIX6/9W8QWxpb/WLl+YpfTZ4MiQ/du8fHeinAksBjnsCYQSaZFH3RwAuewWmaX6HMBMCI30qQELY8+YKwIvbDuN4XSDgVXWZUFfQs8YdsRrU4s4yYc2VmsA643uTX1hDSlItZkS3I9MjQNz0uQudYAJ1Dvu53tYaM3Bupe8rd19RBVLI1DwRpN3Klq8XaRREt+FyYiyPzGHVTFTfg5mvsAWO9MZmT/No176Ple1ZKTQvEXN5k3d/wLCxBqyBEDOkDRkzs7FcbmlSo1NhKn9WAxB/pRkuxUUed2QzFHemzGQYLamVbkMw84X1+kW6XZ'
