server:
  port: 8085

spring:
  datasource:
    url: '{cipher}AQANAy0K4+eYPQRJTsz0CJNHhayhIKi9QTnfJn7/r0EXMGjruuR/ZltcEtqtZl6j2gghyPmLwkbFlHIAKr+bxFMu9IE7BSmiCE3fhUTuSVjtcRcTM/xZ1XCyGEYZNP7y5nsG+QKfZzVHg0gOy6j+Ipdh/sh2sCHlxOC52DZM0fw4Lr7jNBEIAGgFB+J9JbMYxVcXOhiS8+hdQu1D/2rMGR36NOvQ3AxmD+HcZrvlVAoFS8xSjQ80TKTnpKjdDJi3oq6BJIVL16o+YnXzs5RMMFXRY+LukD1OLb1N7cuKHxSjseoVUvoIKF/uLEuwAMvpkoz+/HwwxUqsHFPDAvT9rYyoiUZH4Zd3+UAJi1lDyQABw2hle/9xts/ZBtWAtl+9caVGHlcbY25LqLIe3tkn6JWGj7jhCXmjbWBtrlmuH+w/RwO8o3Ntdeqk22GfRASe50U='

bpmn:
  ribbon:
    listOfServers: http://192.168.0.48:9999