server:
  port: 8086

spring:
  datasource:
    url: '{cipher}AQCHPrd3+VV3XvnIOWOJyeyu3iXOLjYr1NElux+0Pt3F9o6YsCEbZgaUC19sf5jas0wfiJZ2FPSNUu1rCZZPSoXTL14mCBSiLwSTPfkw2dLQpbphxeQAeYs4Vwm40VGAo+dM62TIf/ZLd/10HhskIkYzJSPQOiqsKGG3mG25VufCcsnn+bWNeowsvg5NZOZF9e9nhmp/NOgE0C9j4GClKd642Vy6RIN8vVqQBqagPTdIW/A4ArCfstC7BSWad9ARNybUb9v2MEmoYkWjpNNud+15fNIc80dv+V/CEhb3wnv6K8MPSc8d0rmJfucOSlOKwIPfS3AmQ04EV8v0tvHVz2miOzUQP94gPj0bOi5pvSZ9yBi9CT4edtti9qcqEqvg4MDRzzV4jkq8ZQHvRQ6F2TkAn29xz7lqeUdrmOG1XRdihYTAiOpd3CGyENP7l79hw0U='

bpmn:
  ribbon:
    listOfServers: http://192.168.0.48:9999