server:
  port: 8081

spring:
  datasource:
    url: '{cipher}AQAMZ4y4Z9azBzPQyok6oFOtMe1nBNFtBJC+1Wiq6FaILE7B8KYwGXyRvOylOFRuXhx9jWHC79StsU7nR14yyjzGy2JVtAv8hh/tmDiWKyUTAMMzcOGh3LLEddhLSKwU7qZ9CGLgdj+OWpdi/psn2ocuom58L0kc0MTq4rjetcAIelSYCMNuLGOmni5/1FcUiFuISkaYlX2M507Br4Dwp9qI/+D1Xcz0qslWZIlYrPc3jGNpqPuEQZ4vpyt9uxC04ulhW+R+8khqIfY8s6/iD4RIPhg6HdvfHjUHd7FCVoKah/2KFLO2CQ8E1YgHF1ucsXIdutg1T4u+cf8ojtMaXmswtvVjVNtP/61Iz+q6C5pq9e0Z/C7K+pSb7dJokUx0fVRKAUX8Hw5I6evYy3uBeu/lemyWJT1skwTts31B9a1RjQewrKM9f0H56EhfPSYGbZE='

user:
  register:
    enabled: true
  password:
    random-password-length: 6
    reset-code:
      validity: 86400
      length: 32
      header: FORGOT PASSWORD
      template: USER_PASSWORD_RETRIEVE_TEMPLATE
    update:
      mail:
        enabled: true
        header: PASSWORD UPDATE
        template: USER_PASSWORD_MAIL_TEMPLATE
      sms:
        enabled: false
        template: USER_PASSWORD_SMS_TEMPLATE
    reset:
      mail:
        enabled: true
        header: PASSWORD RESET
        template: USER_PASSWORD_RESET_MAIL_TEMPLATE
      sms:
        enabled: false
        template: USER_PASSWORD_RESET_SMS_TEMPLATE
  exception:
    empty-password: Password should not be empty when mail activation is disabled
  activation:
    mail:
      enabled: true
      token-length: 32
      header: EMAIL ACTIVATION
      template: ACTIVATION_MAIL_TEMPLATE
    sms:
      enabled: false
      token-length: 4
      template: ACTIVATION_SMS_TEMPLATE


cms:
  ribbon:
    listOfServers: http://192.168.0.20:8082

notification:
  ribbon:
    listOfServers: http://192.168.0.20:8003

bpmn:
  ribbon:
    listOfServers: http://192.168.0.20:9999