server:
  port: 8084

spring:
  datasource:
    url: '{cipher}AQBjXQnWL/v+/6Ko4gDcNsX6EXMd2/T7ah/qKgwGSG77xEpMJwqZutbz8pmxxwHhUoEyVfA5FqJwJDZJxm7Q0Rx4S/hMBfSdRCx33/szFhJPwtTp2+rXV+ygIDtMGZAQ3EkMDqh4XBEq8ZFKuee6HgRBvvCXeVWGErLtsVHvK1LwkHSGCURbCM50kWAuNH+X5XXIP/+29JR+wW/ewc0eXtpxxiWmg2mrykiSyYsE6AW36/1OA6zhWkegX3/Y1G2lzTV3RtpUoSHsMMc8G+uyrckFlqjj/hsKeY+CY6S15mnUMHHT9PJcUXzlRtoyKx6iKbubF8U9TsNFcXONqPag75AvvkUdOhn5aWMLEuxLJUggqxm6vukmwqjKm750ndrZD2olYKNxYlZT1aRtuuWduWz+4PXQjvAxNWDUyLEji6Mc/J7dSJwoExaW3+w7GIelFbQ=['

bpmn:
  ribbon:
    listOfServers: http://192.168.0.125:9999